server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:./demo
    username: user
    password: password
    driverClassName: org.h2.Driver


  jpa:
    defer-datasource-initialization: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true


